MVC_SHOP/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MVC_SHOP.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="SuperAdmin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVC_SHOP/Areas/Admin/Controllers/PersonController.cs
using Business.CustomExceptions;
using Business.Services.Abstracts;
using Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MVC_SHOP.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="SuperAdmin")]
    public class PersonController : Controller
    {
        private readonly IPersonService _personService;

        public PersonController(IPersonService personService)
        {
            _personService = personService;
        }

        public IActionResult Index()
        {
            List<Person> people=_personService.GetAll();
            return View(people);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Person person)
        {
            if (!ModelState.IsValid) return View();
            try
            {
                _personService.AddPerson(person);
            }
            catch(EntityNullException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch(ContentTypeException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }

            catch(FileLengthException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch(Exception ex)
            {
                return BadRequest();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            if (!ModelState.IsValid) return View();
            try
            {
                _personService.DeletePerson(id);
            }
            catch(EntityNullException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch(PersonNotFoundException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch(Exception ex)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
            
        }

        public IActionResult Update(int id)
        {
            var person = _personService.GetPerson(x => x.Id == id);
            if(person == null)
            {
                ModelState.AddModelError("", "sss");
                return View();
            }
            return View(person);
        }

        [HttpPost]

        public IActionResult Update(Person person)
        {
            try
            {
                _personService.UpdatePerson(person.Id, person);
            }
            catch (EntityNullException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch (ContentTypeException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }

            catch (FileLengthException ex)
            {
                ModelState.AddModelError(ex.V, ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));


        }

    }
}

MVC_SHOP/Controllers/AccountController.cs
using Core.Models;
using Data.DTOs.AccountDto;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MVC_SHOP.Controllers
{
    
    public class AccountController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AccountController(UserManager<User> userManager, SignInManager<User> signInManager, RoleManager<IdentityRole> roleManager = null)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }
       
        public async Task<IActionResult> Register(RegisterDto registerDto)
        {
            if (!ModelState.IsValid) return View();
            User newUser = new User()
            {
                UserName = registerDto.UserName,
                Email = registerDto.Email,
                Name = registerDto.Name,
                Surname = registerDto.Surname,
            };
            var result = await _userManager.CreateAsync(newUser,registerDto.Password);
            if (!result.Succeeded)
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
                return View();
            }
            await _signInManager.SignInAsync(newUser, false);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Login(LoginDto loginDto)
        {
            if (!ModelState.IsValid) return View();
            var user = await _userManager.FindByNameAsync(loginDto.Username);
            if (user == null)
            {
                ModelState.AddModelError("", "Username adi yanlisdir ve ya yoxdur");
                return View();
            }
            var result = await _signInManager.PasswordSignInAsync(user, loginDto.Password, loginDto.IsRemember, false);

            return RedirectToAction("index", "Home");
        }

        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        //public async Task<IActionResult> CreateRole()
        //{
        //    IdentityRole role=new IdentityRole("SuperAdmin");
        //    IdentityRole role2 = new IdentityRole("Admin");
        //    IdentityRole role1 = new IdentityRole("Member");

        //    await _roleManager.CreateAsync(role);
        //    await _roleManager.CreateAsync(role1);
        //    await _roleManager.CreateAsync(role2);

        //    return Ok("Rollarrr Yarandiiiiiiiiiii");

        //}

        //public async Task<IActionResult> AddRole()
        //{
        //    var role = await _userManager.FindByNameAsync("ramazann");
        //    await _userManager.AddToRoleAsync(role, "SuperAdmin");
        //    return Ok("Rolll verildiiii!!!!!!!!!!!");
        //}

    }
}

MVC_SHOP/Controllers/HomeController.cs
using Business.Services.Abstracts;
using Core.Models;
using Microsoft.AspNetCore.Mvc;

using System.Diagnostics;

namespace MVC_SHOP.Controllers
{
    public class HomeController : Controller
    {
        
        private readonly IPersonService _personService;

        public HomeController(IPersonService personService)
        {
            _personService = personService;
        }

        public IActionResult Index()
        {
            List<Person> persons = _personService.GetAll();
            return View(persons);
        }

       
    }
}

MVC_SHOP/Areas/Admin/Views/Person/Create.cshtml
@using Core.Models
@model Person

<div class="container">

    <form method="post" enctype="multipart/form-data">
    <div class="row">


            <div class="mb-3 col-md-4">
              
              <label asp-for="FullName">Fullname</label>
              <input class="form-control" asp-for="FullName">   
              <span asp-validation-for="FullName"></span>
         </div>
            <div class="mb-3 col-md-4">

            <label asp-for="Title">Title</label>
            <input class="form-control" asp-for="Title">
            <span asp-validation-for="Title"></span>
        </div>

            <div class="mb-3 col-md-4">
            <label asp-for="PhotoFile" class="form-label"> Image </label>
            <input asp-for="PhotoFile" class="form-control">
            <span asp-validation-for="PhotoFile" style="color:darkred"></span>
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>

    </div>
    </form>

</div>

MVC_SHOP/Areas/Admin/Views/Person/Index.cshtml
@using Core.Models

@model List<Person>
@{
    int count = 0;
}

<h1>

    Persons
    <a asp-action="Create" class="btn btn-dark">Create</a>

</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">FullName</th>
            <th scope="col">Title</th>
            <th scope="col">Image</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model){
            count++;
            <tr>
            <th scope="row">@count</th>
            <td>@item.FullName</td>
            <td>@item.Title</td>
            <td>
                <div style="width:100px">
                <img src="~/Upload/Person/@item.ImgUrl"  width="100%"/>
                    </div>
            </td>
            <td>
                    <a class="btn btn-danger" asp-action="Update" asp-controller="Person" asp-route-id=@item.Id>Update</a>
                    <a class="btn btn-primary" asp-action="Delete" asp-controller="Person" asp-route-id=@item.Id>Delete</a>

            </td>
            
            
        </tr>
        }
       
    </tbody>
</table>

MVC_SHOP/Areas/Admin/Views/Person/Update.cshtml
@using Core.Models
@model Person

<div class="container">

    <form method="post" enctype="multipart/form-data">
        <div class="row">


            <div class="mb-3 col-md-4">

                <label asp-for="FullName">Fullname</label>
                <input class="form-control" asp-for="FullName">
                <span asp-validation-for="FullName"></span>
            </div>
            <div class="mb-3 col-md-4">

                <label asp-for="Title">Title</label>
                <input class="form-control" asp-for="Title">
                <span asp-validation-for="Title"></span>
            </div>

            <div class="mb-3 col-md-4">
                <label asp-for="PhotoFile" class="form-label"> Image </label>
                <input asp-for="PhotoFile" class="form-control">
                <span asp-validation-for="PhotoFile" style="color:darkred"></span>
            </div>

            
            <button type="submit" class="btn btn-primary">Submit</button>

        </div>
    </form>

</div>

MVC_SHOP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>PET SHOP - Pet Shop Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/flaticon/font/flaticon.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid border-bottom d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-lg-4 text-center py-2">
                <div class="d-inline-flex align-items-center">
                    <i class="bi bi-geo-alt fs-1 text-primary me-3"></i>
                    <div class="text-start">
                        <h6 class="text-uppercase mb-1">Our Office</h6>
                        <span>123 Street, New York, USA</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-center border-start border-end py-2">
                <div class="d-inline-flex align-items-center">
                    <i class="bi bi-envelope-open fs-1 text-primary me-3"></i>
                    <div class="text-start">
                        <h6 class="text-uppercase mb-1">Email Us</h6>
                        <span>info@example.com</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-center py-2">
                <div class="d-inline-flex align-items-center">
                    <i class="bi bi-phone-vibrate fs-1 text-primary me-3"></i>
                    <div class="text-start">
                        <h6 class="text-uppercase mb-1">Call Us</h6>
                        <span>+012 345 6789</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <a href="index.html" class="navbar-brand ms-lg-5">
            <h1 class="m-0 text-uppercase text-dark"><i class="bi bi-shop fs-1 text-primary me-3"></i>Pet Shop</h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="index.html" class="nav-item nav-link active">Home</a>
                <a href="about.html" class="nav-item nav-link">About</a>
                <a href="service.html" class="nav-item nav-link">Service</a>
                <a href="product.html" class="nav-item nav-link">Product</a>
                @if(User.Identity.IsAuthenticated){
                    <a  class="nav-item nav-link" asp-action="LogOut" asp-controller="Account">LogOut</a>
                    
                }
                else{
                    <a class="nav-item nav-link" asp-action="Login" asp-controller="Account">Login</a>
                    <a  class="nav-item nav-link" asp-action="Register" asp-controller="Account">register</a>
                }
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu m-0">
                        <a href="price.html" class="dropdown-item">Pricing Plan</a>
                        <a href="team.html" class="dropdown-item">The Team</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                        <a href="blog.html" class="dropdown-item">Blog Grid</a>
                        <a href="detail.html" class="dropdown-item">Blog Detail</a>
                    </div>
                </div>
                <a href="contact.html" class="nav-item nav-link nav-contact bg-primary text-white px-5 ms-lg-5">Contact <i class="bi bi-arrow-right"></i></a>
            </div>
        </div>
    </nav>
    <!-- Navbar End -->
            @RenderBody()
            <!-- Footer Start -->
            <div class="container-fluid bg-light mt-5 py-5">
                <div class="container pt-5">
                    <div class="row g-5">
                        <div class="col-lg-3 col-md-6">
                            <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">Get In Touch</h5>
                            <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor</p>
                            <p class="mb-2"><i class="bi bi-geo-alt text-primary me-2"></i>123 Street, New York, USA</p>
                            <p class="mb-2"><i class="bi bi-envelope-open text-primary me-2"></i>info@example.com</p>
                            <p class="mb-0"><i class="bi bi-telephone text-primary me-2"></i>+012 345 67890</p>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">Quick Links</h5>
                            <div class="d-flex flex-column justify-content-start">
                                <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                                <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                                <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                                <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Meet The Team</a>
                                <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest Blog</a>
                                <a class="text-body" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">Popular Links</h5>
                            <div class="d-flex flex-column justify-content-start">
                                <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                                <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                                <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                                <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Meet The Team</a>
                                <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest Blog</a>
                                <a class="text-body" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">Newsletter</h5>
                            <form action="">
                                <div class="input-group">
                                    <input type="text" class="form-control p-3" placeholder="Your Email">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </form>
                            <h6 class="text-uppercase mt-4 mb-3">Follow Us</h6>
                            <div class="d-flex">
                                <a class="btn btn-outline-primary btn-square me-2" href="#"><i class="bi bi-twitter"></i></a>
                                <a class="btn btn-outline-primary btn-square me-2" href="#"><i class="bi bi-facebook"></i></a>
                                <a class="btn btn-outline-primary btn-square me-2" href="#"><i class="bi bi-linkedin"></i></a>
                                <a class="btn btn-outline-primary btn-square" href="#"><i class="bi bi-instagram"></i></a>
                            </div>
                        </div>
                        <div class="col-12 text-center text-body">
                            <a class="text-body" href="">Terms & Conditions</a>
                            <span class="mx-1">|</span>
                            <a class="text-body" href="">Privacy Policy</a>
                            <span class="mx-1">|</span>
                            <a class="text-body" href="">Customer Support</a>
                            <span class="mx-1">|</span>
                            <a class="text-body" href="">Payments</a>
                            <span class="mx-1">|</span>
                            <a class="text-body" href="">Help</a>
                            <span class="mx-1">|</span>
                            <a class="text-body" href="">FAQs</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid bg-dark text-white-50 py-4">
                <div class="container">
                    <div class="row g-5">
                        <div class="col-md-6 text-center text-md-start">
                            <p class="mb-md-0">&copy; <a class="text-white" href="#">Your Site Name</a>. All Rights Reserved.</p>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <p class="mb-0">Designed by <a class="text-white" href="https://htmlcodex.com">HTML Codex</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
            <!-- Back to Top -->
            <a href="#" class="btn btn-primary py-3 fs-4 back-to-top"><i class="bi bi-arrow-up"></i></a>


            <!-- JavaScript Libraries -->
            <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/lib/easing/easing.min.js"></script>
            <script src="~/lib/waypoints/waypoints.min.js"></script>
            <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

            <!-- Template Javascript -->
            <script src="js/main.js"></script>
</body>

</html>